#!/bin/sh
CODEENGINE_GIT_ASKPASS_PIPE=`mktemp`
ELECTRON_RUN_AS_NODE="1" CODEENGINE_GIT_ASKPASS_PIPE="$CODEENGINE_GIT_ASKPASS_PIPE" CODEENGINE_GIT_ASKPASS_TYPE="ssh" "$CODEENGINE_GIT_ASKPASS_NODE" "$CODEENGINE_GIT_ASKPASS_MAIN" $CODEENGINE_GIT_ASKPASS_EXTRA_ARGS $*
cat $CODEENGINE_GIT_ASKPASS_PIPE
rm $CODEENGINE_GIT_ASKPASS_PIPE
